/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import controlador.Main;
import hibernate.Asistencia;
import hibernate.Dependiente;
import hibernate.TareasPendientes;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.sql.Date;
import java.text.ParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.TableRowSorter;
import modelo.conexion.Conexion;

/**
 *
 * @author vesprada
 */
public class JFramePantallaPrincipal extends javax.swing.JFrame {

    private final Controlador controlador;
    private final Conexion conexion;
    private String idDependienteLlamada;
    private Double longitudDependienteLlamada;
    private Double latitudDependienteLlamada;

    private DefaultTableModel tablaListaDependientes;
    private TableRowSorter trsFiltroDependientes;

    public JFramePantallaPrincipal(Controlador controlador, Conexion conexion) {
        super("DependenciApp");
        setAspecto("Nimbus");
        initComponents();
        this.controlador = controlador;
        this.conexion = conexion;
        setUI();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAñadirTarea = new javax.swing.JDialog();
        jComboBoxDependientesAddTarea = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooserComboFechaAddTarea = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldHoraAddTarea = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEncabezadoAddTarea = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescripcionAddTarea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButtonCrearTareaAddTarea = new javax.swing.JButton();
        jFormattedTextFieldHorasRepeticion = new javax.swing.JFormattedTextField();
        jCheckBoxAsistente = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jDialogDetallesLlamada = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabelDependienteDetallesLlamada = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateChooserComboFechaDetallesLlamada = new datechooser.beans.DateChooserCombo();
        jTextFieldMotivoDetallesLlamada = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaDatosAsistenciaDetallesLlamada = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButtonAceptarDetallesLlamada = new javax.swing.JButton();
        jDialogAlertaLlamadaEntrante = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonCogerLlamadaAviso = new javax.swing.JButton();
        jDialogCrearDependiente = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldDNICrearDependiente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNombreCrearDependiente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldApellidosCrearDependiente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dateChooserComboNacimientoCrearDependiente = new datechooser.beans.DateChooserCombo();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxGeneroCrearDependiente = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxTipoCrearDependiente = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPasswordFieldCrearDependiente = new javax.swing.JPasswordField();
        jButtonCrearDependiente = new javax.swing.JButton();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelAgenda = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAgenda = new javax.swing.JTable();
        jButtonAddTarea = new javax.swing.JButton();
        jButtonTareaRealizado = new javax.swing.JButton();
        jButtonBorrarTarea = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldBuscadorTarea = new javax.swing.JTextField();
        jPanelHistorialLlamadas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHistorialLlamadas = new javax.swing.JTable();
        jButtonVerDetallesLlamada = new javax.swing.JButton();
        jButtonVerDependienteHist = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldBuscadorLlamada = new javax.swing.JTextField();
        jPanelDependientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDependientes = new javax.swing.JTable();
        jButtonVerDependiente = new javax.swing.JButton();
        jButtonAddDependiente = new javax.swing.JButton();
        jButtonBorrarDependiente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBuscadorDependiente = new javax.swing.JTextField();

        jComboBoxDependientesAddTarea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Dependiente");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Hora");

        jFormattedTextFieldHoraAddTarea.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldHoraAddTarea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Encabezado");

        jTextFieldEncabezadoAddTarea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextAreaDescripcionAddTarea.setColumns(20);
        jTextAreaDescripcionAddTarea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaDescripcionAddTarea.setLineWrap(true);
        jTextAreaDescripcionAddTarea.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescripcionAddTarea);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Descripción");

        jButtonCrearTareaAddTarea.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonCrearTareaAddTarea.setText("Crear");
        jButtonCrearTareaAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTareaAddTareaActionPerformed(evt);
            }
        });

        jFormattedTextFieldHorasRepeticion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        jFormattedTextFieldHorasRepeticion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jCheckBoxAsistente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxAsistente.setText("Tarea de Asistente");
        jCheckBoxAsistente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBoxAsistente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBoxAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAsistenteActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Repetición (horas)");

        javax.swing.GroupLayout jDialogAñadirTareaLayout = new javax.swing.GroupLayout(jDialogAñadirTarea.getContentPane());
        jDialogAñadirTarea.getContentPane().setLayout(jDialogAñadirTareaLayout);
        jDialogAñadirTareaLayout.setHorizontalGroup(
            jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAñadirTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAsistente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxDependientesAddTarea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooserComboFechaAddTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEncabezadoAddTarea)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jButtonCrearTareaAddTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogAñadirTareaLayout.createSequentialGroup()
                        .addGroup(jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldHoraAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogAñadirTareaLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jFormattedTextFieldHorasRepeticion))))
                .addContainerGap())
        );
        jDialogAñadirTareaLayout.setVerticalGroup(
            jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAñadirTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDependientesAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserComboFechaAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAñadirTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldHoraAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldHorasRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldEncabezadoAddTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearTareaAddTarea)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Dependiente:");

        jLabelDependienteDetallesLlamada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelDependienteDetallesLlamada.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Fecha:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Motivo:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Datos de Asistencia:");

        dateChooserComboFechaDetallesLlamada.setLocked(true);

        jTextFieldMotivoDetallesLlamada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextAreaDatosAsistenciaDetallesLlamada.setColumns(20);
        jTextAreaDatosAsistenciaDetallesLlamada.setLineWrap(true);
        jTextAreaDatosAsistenciaDetallesLlamada.setRows(5);
        jScrollPane5.setViewportView(jTextAreaDatosAsistenciaDetallesLlamada);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Detalles Llamada");

        jButtonAceptarDetallesLlamada.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonAceptarDetallesLlamada.setText("Aceptar");
        jButtonAceptarDetallesLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarDetallesLlamadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogDetallesLlamadaLayout = new javax.swing.GroupLayout(jDialogDetallesLlamada.getContentPane());
        jDialogDetallesLlamada.getContentPane().setLayout(jDialogDetallesLlamadaLayout);
        jDialogDetallesLlamadaLayout.setHorizontalGroup(
            jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                        .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMotivoDetallesLlamada)
                            .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                                .addComponent(dateChooserComboFechaDetallesLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                        .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDependienteDetallesLlamada))
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialogDetallesLlamadaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAceptarDetallesLlamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogDetallesLlamadaLayout.setVerticalGroup(
            jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogDetallesLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelDependienteDetallesLlamada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(dateChooserComboFechaDetallesLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogDetallesLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldMotivoDetallesLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptarDetallesLlamada)
                .addContainerGap())
        );

        jDialogAlertaLlamadaEntrante.setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 245, 157));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("AVISO - LLAMADA ENTRANTE");

        jButtonCogerLlamadaAviso.setBackground(new java.awt.Color(244, 67, 54));
        jButtonCogerLlamadaAviso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonCogerLlamadaAviso.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCogerLlamadaAviso.setText("COGER LLAMADA");
        jButtonCogerLlamadaAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCogerLlamadaAvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCogerLlamadaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jButtonCogerLlamadaAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAlertaLlamadaEntranteLayout = new javax.swing.GroupLayout(jDialogAlertaLlamadaEntrante.getContentPane());
        jDialogAlertaLlamadaEntrante.getContentPane().setLayout(jDialogAlertaLlamadaEntranteLayout);
        jDialogAlertaLlamadaEntranteLayout.setHorizontalGroup(
            jDialogAlertaLlamadaEntranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogAlertaLlamadaEntranteLayout.setVerticalGroup(
            jDialogAlertaLlamadaEntranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("DNI");

        jTextFieldDNICrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel14.setText("Nombre");

        jTextFieldNombreCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Apellidos");

        jTextFieldApellidosCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Nacimiento");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Genero");

        jComboBoxGeneroCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxGeneroCrearDependiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "H", "I" }));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Tipo");

        jComboBoxTipoCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxTipoCrearDependiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enf. Cronico", "Persona Mayor", "Discapacidad", "Violencia de genero" }));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Contraseña");

        jPasswordFieldCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButtonCrearDependiente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonCrearDependiente.setText("Crear Dependiente");
        jButtonCrearDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDependienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogCrearDependienteLayout = new javax.swing.GroupLayout(jDialogCrearDependiente.getContentPane());
        jDialogCrearDependiente.getContentPane().setLayout(jDialogCrearDependienteLayout);
        jDialogCrearDependienteLayout.setHorizontalGroup(
            jDialogCrearDependienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCrearDependienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogCrearDependienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDNICrearDependiente)
                    .addComponent(jTextFieldNombreCrearDependiente)
                    .addComponent(jTextFieldApellidosCrearDependiente)
                    .addComponent(dateChooserComboNacimientoCrearDependiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxGeneroCrearDependiente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTipoCrearDependiente, 0, 277, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldCrearDependiente)
                    .addGroup(jDialogCrearDependienteLayout.createSequentialGroup()
                        .addGroup(jDialogCrearDependienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonCrearDependiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogCrearDependienteLayout.setVerticalGroup(
            jDialogCrearDependienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCrearDependienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDNICrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidosCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserComboNacimientoCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxGeneroCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipoCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldCrearDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearDependiente, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPanePrincipal.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jTableAgenda.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAgenda.setRowHeight(18);
        jScrollPane3.setViewportView(jTableAgenda);

        jButtonAddTarea.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonAddTarea.setText("Añadir Tarea");
        jButtonAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTareaActionPerformed(evt);
            }
        });

        jButtonTareaRealizado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonTareaRealizado.setText("Tarea Realizada");
        jButtonTareaRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTareaRealizadoActionPerformed(evt);
            }
        });

        jButtonBorrarTarea.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonBorrarTarea.setText("Borrar Tarea");
        jButtonBorrarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTareaActionPerformed(evt);
            }
        });

        jButton1.setText("pruebaAviso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Buscar Tarea por Dependiente:");

        jTextFieldBuscadorTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscadorTareaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgendaLayout = new javax.swing.GroupLayout(jPanelAgenda);
        jPanelAgenda.setLayout(jPanelAgendaLayout);
        jPanelAgendaLayout.setHorizontalGroup(
            jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(jPanelAgendaLayout.createSequentialGroup()
                        .addComponent(jButtonAddTarea)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTareaRealizado)
                        .addGap(98, 98, 98)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarTarea))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscadorTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelAgendaLayout.setVerticalGroup(
            jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldBuscadorTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddTarea)
                    .addComponent(jButtonTareaRealizado)
                    .addComponent(jButtonBorrarTarea)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPanePrincipal.addTab("Agenda", jPanelAgenda);

        jTableHistorialLlamadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableHistorialLlamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableHistorialLlamadas.setRowHeight(18);
        jScrollPane2.setViewportView(jTableHistorialLlamadas);

        jButtonVerDetallesLlamada.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonVerDetallesLlamada.setText("Ver Detalles");
        jButtonVerDetallesLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDetallesLlamadaActionPerformed(evt);
            }
        });

        jButtonVerDependienteHist.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonVerDependienteHist.setText("Ver Dependiente");
        jButtonVerDependienteHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDependienteHistActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Buscar Llamada por Dependiente:");

        jTextFieldBuscadorLlamada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscadorLlamadaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelHistorialLlamadasLayout = new javax.swing.GroupLayout(jPanelHistorialLlamadas);
        jPanelHistorialLlamadas.setLayout(jPanelHistorialLlamadasLayout);
        jPanelHistorialLlamadasLayout.setHorizontalGroup(
            jPanelHistorialLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialLlamadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHistorialLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(jPanelHistorialLlamadasLayout.createSequentialGroup()
                        .addComponent(jButtonVerDetallesLlamada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerDependienteHist)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistorialLlamadasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscadorLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelHistorialLlamadasLayout.setVerticalGroup(
            jPanelHistorialLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialLlamadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHistorialLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldBuscadorLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHistorialLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerDetallesLlamada)
                    .addComponent(jButtonVerDependienteHist))
                .addContainerGap())
        );

        jTabbedPanePrincipal.addTab("Historial Llamadas", jPanelHistorialLlamadas);

        jTableListaDependientes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableListaDependientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableListaDependientes.setRowHeight(18);
        jScrollPane1.setViewportView(jTableListaDependientes);

        jButtonVerDependiente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonVerDependiente.setText("Ver Dependiente");
        jButtonVerDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDependienteActionPerformed(evt);
            }
        });

        jButtonAddDependiente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonAddDependiente.setText("Añadir Dependiente");
        jButtonAddDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDependienteActionPerformed(evt);
            }
        });

        jButtonBorrarDependiente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButtonBorrarDependiente.setText("Borrar Dependiente");
        jButtonBorrarDependiente.setEnabled(false);
        jButtonBorrarDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarDependienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Buscar Dependiente:");

        jTextFieldBuscadorDependiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscadorDependienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelDependientesLayout = new javax.swing.GroupLayout(jPanelDependientes);
        jPanelDependientes.setLayout(jPanelDependientesLayout);
        jPanelDependientesLayout.setHorizontalGroup(
            jPanelDependientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDependientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDependientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDependientesLayout.createSequentialGroup()
                        .addComponent(jButtonAddDependiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerDependiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarDependiente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDependientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscadorDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDependientesLayout.setVerticalGroup(
            jPanelDependientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDependientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDependientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldBuscadorDependiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDependientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerDependiente)
                    .addComponent(jButtonAddDependiente)
                    .addComponent(jButtonBorrarDependiente))
                .addContainerGap())
        );

        jTabbedPanePrincipal.addTab("Dependientes", jPanelDependientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTareaActionPerformed
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(this.controlador.getListaDependientes().toArray());
        jComboBoxDependientesAddTarea.setModel(dcbm);
        this.controlador.abreDialog(jDialogAñadirTarea, false);

    }//GEN-LAST:event_jButtonAddTareaActionPerformed

    private void jButtonTareaRealizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTareaRealizadoActionPerformed
        if (this.jTableAgenda.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(this, "Seguro que quieres marcar esta tarea como realizada?") == JOptionPane.YES_OPTION) {
                this.conexion.estableceLaTareaRealizada((TareasPendientes) this.jTableAgenda.getValueAt(this.jTableAgenda.getSelectedRow(), 0));
                this.controlador.rellenaTablaAgenda(jTableAgenda);
            }
        }
    }//GEN-LAST:event_jButtonTareaRealizadoActionPerformed

    private void jButtonBorrarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTareaActionPerformed
        if (this.jTableAgenda.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(this, "Seguro que quieres borrar esta tarea?") == JOptionPane.YES_OPTION) {
                TareasPendientes tarea = (TareasPendientes) this.jTableAgenda.getModel().getValueAt(this.jTableAgenda.getSelectedRow(), 0);
                this.controlador.borraTarea(tarea);
                DefaultTableModel model = (DefaultTableModel) this.jTableAgenda.getModel();
                model.removeRow(this.jTableAgenda.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonBorrarTareaActionPerformed

    private void jButtonVerDetallesLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDetallesLlamadaActionPerformed
        //TODO funcion por especificar (no se sabe si se va a poder editar una llamada en el historial o no)
        if (this.jTableHistorialLlamadas.getSelectedRow() != -1) {
            Asistencia asis = (Asistencia) this.jTableHistorialLlamadas.getModel().getValueAt(this.jTableHistorialLlamadas.getSelectedRow(), 0);
            jLabelDependienteDetallesLlamada.setText(asis.getDependiente().toString());
            dateChooserComboFechaDetallesLlamada.setText(asis.getFecha().toString());
            jTextFieldMotivoDetallesLlamada.setText(asis.getMotivo());
            jTextAreaDatosAsistenciaDetallesLlamada.setText(asis.getDatosAsistencia());

            this.controlador.abreDialog(jDialogDetallesLlamada, false);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna llamada");
        }
    }//GEN-LAST:event_jButtonVerDetallesLlamadaActionPerformed

    private void jButtonVerDependienteHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDependienteHistActionPerformed

        if (this.jTableHistorialLlamadas.getSelectedRow() != -1) {
            Asistencia asis = (Asistencia) this.jTableHistorialLlamadas.getModel().getValueAt(this.jTableHistorialLlamadas.getSelectedRow(), 0);
            this.controlador.abreFrame(new JFrameDependiente(controlador, asis.getDependiente()));
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dependiente");
        }
    }//GEN-LAST:event_jButtonVerDependienteHistActionPerformed

    private void jButtonVerDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDependienteActionPerformed
        if (this.jTableListaDependientes.getSelectedRow() != -1) {
            this.controlador.abreFrame(new JFrameDependiente(controlador, (Dependiente) this.jTableListaDependientes.getModel().getValueAt(this.jTableListaDependientes.getSelectedRow(), 0)));
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dependiente");
        }

    }//GEN-LAST:event_jButtonVerDependienteActionPerformed

    private void jButtonCrearTareaAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTareaAddTareaActionPerformed

        Dependiente dependiente = (Dependiente) jComboBoxDependientesAddTarea.getSelectedItem();
        Calendar fecha = dateChooserComboFechaAddTarea.getSelectedDate();
        String hora = jFormattedTextFieldHoraAddTarea.getText();
        String encabezado = jTextFieldEncabezadoAddTarea.getText();
        String descripcion = jTextAreaDescripcionAddTarea.getText();
        String fechaHora = fecha.getInstance().get(Calendar.YEAR) + "-" + fecha.getInstance().get(Calendar.MONTH) + "-" + fecha.getInstance().get(Calendar.DAY_OF_MONTH) + " " + hora;

        Double horasRepeticon = jFormattedTextFieldHorasRepeticion.getText().equals("") ? null : Double.parseDouble(jFormattedTextFieldHorasRepeticion.getText());

        try {
            this.controlador.crearTareaMedicina(dependiente, Controlador.parseaFecha(fechaHora), encabezado, descripcion, horasRepeticon, jCheckBoxAsistente.isSelected(), false);
        } catch (ParseException ex) {
            Logger.getLogger(JFramePantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.jDialogAñadirTarea.dispose();
        this.controlador.rellenaTablaAgenda(jTableAgenda);


    }//GEN-LAST:event_jButtonCrearTareaAddTareaActionPerformed

    private void jButtonAceptarDetallesLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarDetallesLlamadaActionPerformed
        //TODO --- si se puede editar el historial de llamadas, hay que hacer o otro dialog o bien modificar este (jDialogDetallesLlamada)
        if (this.idDependienteLlamada != null) {
            String motivo = jTextFieldMotivoDetallesLlamada.getText();
            String datos = jTextAreaDatosAsistenciaDetallesLlamada.getText();
            Asistencia asistencia = new Asistencia(this.controlador.getConexion().getDependienteById(idDependienteLlamada), Calendar.getInstance().getTime(), motivo, datos);
            this.controlador.crearAsistencia(asistencia);
            this.idDependienteLlamada = null;
            DefaultTableModel dtm = (DefaultTableModel) jTableHistorialLlamadas.getModel();
            dtm.addRow(asistencia.getAsistenciaForTable());
        }
        jDialogDetallesLlamada.dispose();

    }//GEN-LAST:event_jButtonAceptarDetallesLlamadaActionPerformed

    private void jButtonCogerLlamadaAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCogerLlamadaAvisoActionPerformed

        jDialogAlertaLlamadaEntrante.dispose();

        JFrameDependienteLlamada jfdl = new JFrameDependienteLlamada(controlador, this.controlador.getConexion().getDependienteById(this.idDependienteLlamada), this.longitudDependienteLlamada, this.latitudDependienteLlamada, this.jTableHistorialLlamadas);
        this.controlador.abreFrame(jfdl);


    }//GEN-LAST:event_jButtonCogerLlamadaAvisoActionPerformed

    private void jButtonCrearDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDependienteActionPerformed
        // TODO add your handling code here:
        //Enf. Cronico, Persona Mayor, Discapacidad, Violencia de genero
        String dni = jTextFieldDNICrearDependiente.getText();
        String nombre = jTextFieldNombreCrearDependiente.getText();
        String apellidos = jTextFieldApellidosCrearDependiente.getText();
        Calendar fechaNac = dateChooserComboNacimientoCrearDependiente.getCurrent();
        String genero = (String) jComboBoxGeneroCrearDependiente.getSelectedItem();
        String tipo = (String) jComboBoxTipoCrearDependiente.getSelectedItem();
        String pass = new String(jPasswordFieldCrearDependiente.getPassword()); //TODO comprobar si esta cogiendo bien la contraseña

        this.controlador.crearDependiente(dni, nombre, apellidos, fechaNac, genero, tipo, pass, (DefaultTableModel) jTableListaDependientes.getModel());
        jDialogCrearDependiente.dispose();


    }//GEN-LAST:event_jButtonCrearDependienteActionPerformed

    private void jButtonAddDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDependienteActionPerformed
        // TODO add your handling code here:
        this.controlador.abreDialog(jDialogCrearDependiente, false);
    }//GEN-LAST:event_jButtonAddDependienteActionPerformed

    private void jButtonBorrarDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarDependienteActionPerformed
        if (this.jTableListaDependientes.getSelectedRow() != -1) {
            int s = this.jTableListaDependientes.getSelectedRow();
            Dependiente d = (Dependiente) this.jTableListaDependientes.getModel().getValueAt(this.jTableListaDependientes.getSelectedRow(), 0);
            if (JOptionPane.showConfirmDialog(this, "Seguro que quieres borrar a " + d.toString()) == JOptionPane.YES_OPTION) {
                this.controlador.getConexion().eliminaDependiente(d);
                DefaultTableModel tabla = (DefaultTableModel) jTableListaDependientes.getModel();
                tabla.removeRow(s);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dependiente");
        }
    }//GEN-LAST:event_jButtonBorrarDependienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        abreDialogAlerta("1", "-0.484756", "38.346041");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldBuscadorDependienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorDependienteKeyTyped
        trsFiltroDependientes = new TableRowSorter(jTableListaDependientes.getModel());
        trsFiltroDependientes.setRowFilter(RowFilter.regexFilter(jTextFieldBuscadorDependiente.getText(), 0));
        jTableListaDependientes.setRowSorter(trsFiltroDependientes);

    }//GEN-LAST:event_jTextFieldBuscadorDependienteKeyTyped

    private void jTextFieldBuscadorLlamadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorLlamadaKeyTyped
        trsFiltroDependientes = new TableRowSorter(jTableHistorialLlamadas.getModel());
        trsFiltroDependientes.setRowFilter(RowFilter.regexFilter(jTextFieldBuscadorLlamada.getText(), 0));
        jTableHistorialLlamadas.setRowSorter(trsFiltroDependientes);
    }//GEN-LAST:event_jTextFieldBuscadorLlamadaKeyTyped

    private void jTextFieldBuscadorTareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscadorTareaKeyTyped
        trsFiltroDependientes = new TableRowSorter(jTableAgenda.getModel());
        trsFiltroDependientes.setRowFilter(RowFilter.regexFilter(jTextFieldBuscadorTarea.getText(), 0));
        jTableAgenda.setRowSorter(trsFiltroDependientes);
    }//GEN-LAST:event_jTextFieldBuscadorTareaKeyTyped

    private void jCheckBoxAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAsistenteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.conexion.cierraConexion();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserComboFechaAddTarea;
    private datechooser.beans.DateChooserCombo dateChooserComboFechaDetallesLlamada;
    private datechooser.beans.DateChooserCombo dateChooserComboNacimientoCrearDependiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptarDetallesLlamada;
    private javax.swing.JButton jButtonAddDependiente;
    private javax.swing.JButton jButtonAddTarea;
    private javax.swing.JButton jButtonBorrarDependiente;
    private javax.swing.JButton jButtonBorrarTarea;
    private javax.swing.JButton jButtonCogerLlamadaAviso;
    private javax.swing.JButton jButtonCrearDependiente;
    private javax.swing.JButton jButtonCrearTareaAddTarea;
    private javax.swing.JButton jButtonTareaRealizado;
    private javax.swing.JButton jButtonVerDependiente;
    private javax.swing.JButton jButtonVerDependienteHist;
    private javax.swing.JButton jButtonVerDetallesLlamada;
    private javax.swing.JCheckBox jCheckBoxAsistente;
    private javax.swing.JComboBox<String> jComboBoxDependientesAddTarea;
    private javax.swing.JComboBox<String> jComboBoxGeneroCrearDependiente;
    private javax.swing.JComboBox<String> jComboBoxTipoCrearDependiente;
    private javax.swing.JDialog jDialogAlertaLlamadaEntrante;
    private javax.swing.JDialog jDialogAñadirTarea;
    private javax.swing.JDialog jDialogCrearDependiente;
    private javax.swing.JDialog jDialogDetallesLlamada;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraAddTarea;
    private javax.swing.JFormattedTextField jFormattedTextFieldHorasRepeticion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDependienteDetallesLlamada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAgenda;
    private javax.swing.JPanel jPanelDependientes;
    private javax.swing.JPanel jPanelHistorialLlamadas;
    private javax.swing.JPasswordField jPasswordFieldCrearDependiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTable jTableAgenda;
    private javax.swing.JTable jTableHistorialLlamadas;
    private javax.swing.JTable jTableListaDependientes;
    private javax.swing.JTextArea jTextAreaDatosAsistenciaDetallesLlamada;
    private javax.swing.JTextArea jTextAreaDescripcionAddTarea;
    private javax.swing.JTextField jTextFieldApellidosCrearDependiente;
    private javax.swing.JTextField jTextFieldBuscadorDependiente;
    private javax.swing.JTextField jTextFieldBuscadorLlamada;
    private javax.swing.JTextField jTextFieldBuscadorTarea;
    private javax.swing.JTextField jTextFieldDNICrearDependiente;
    private javax.swing.JTextField jTextFieldEncabezadoAddTarea;
    private javax.swing.JTextField jTextFieldMotivoDetallesLlamada;
    private javax.swing.JTextField jTextFieldNombreCrearDependiente;
    // End of variables declaration//GEN-END:variables

    private void setUI() {

        this.controlador.rellenaTablaAgenda(this.jTableAgenda);
        this.controlador.rellenaTablaHistorialLlamadas(this.jTableHistorialLlamadas);
        this.controlador.rellenaTablaListaDependiente(this.jTableListaDependientes);
        tablaListaDependientes = (DefaultTableModel) jTableListaDependientes.getModel();

    }

    private void setAspecto(String aspecto) {
        //set Nimbus o otro
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (aspecto.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void abreDialogAlerta(String id, String longitud, String latitud) {
        this.idDependienteLlamada = id;
        this.longitudDependienteLlamada = Double.parseDouble(longitud);
        this.latitudDependienteLlamada = Double.parseDouble(latitud);
        jDialogAlertaLlamadaEntrante.pack();
        jDialogAlertaLlamadaEntrante.setModal(true);
        jDialogAlertaLlamadaEntrante.setLocationRelativeTo(null);
        jDialogAlertaLlamadaEntrante.setVisible(true);
    }
    
    

}
