package hibernate;
// Generated 12-feb-2018 18:52:59 by Hibernate Tools 4.3.1



/**
 * Aviso generated by hbm2java
 */
public class Aviso  implements java.io.Serializable {


     private Integer idAviso;
     private Dependiente dependiente;
     private String hora;

    public Aviso() {
    }

	
    public Aviso(Dependiente dependiente) {
        this.dependiente = dependiente;
    }
    public Aviso(Dependiente dependiente, String hora) {
       this.dependiente = dependiente;
       this.hora = hora;
    }
   
    public Integer getIdAviso() {
        return this.idAviso;
    }
    
    public void setIdAviso(Integer idAviso) {
        this.idAviso = idAviso;
    }
    public Dependiente getDependiente() {
        return this.dependiente;
    }
    
    public void setDependiente(Dependiente dependiente) {
        this.dependiente = dependiente;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


