package hibernate;
// Generated 12-feb-2018 18:52:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private Integer idPoblacion;
     private String nombre;
     private String provincia;
     private String pais;
     private Set viviendas = new HashSet(0);
     private RecursosLocalidad recursosLocalidad;

    public Poblacion() {
    }

    public Poblacion(String nombre, String provincia, String pais, Set viviendas, RecursosLocalidad recursosLocalidad) {
       this.nombre = nombre;
       this.provincia = provincia;
       this.pais = pais;
       this.viviendas = viviendas;
       this.recursosLocalidad = recursosLocalidad;
    }
   
    public Integer getIdPoblacion() {
        return this.idPoblacion;
    }
    
    public void setIdPoblacion(Integer idPoblacion) {
        this.idPoblacion = idPoblacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getViviendas() {
        return this.viviendas;
    }
    
    public void setViviendas(Set viviendas) {
        this.viviendas = viviendas;
    }
    public RecursosLocalidad getRecursosLocalidad() {
        return this.recursosLocalidad;
    }
    
    public void setRecursosLocalidad(RecursosLocalidad recursosLocalidad) {
        this.recursosLocalidad = recursosLocalidad;
    }
    public Object[] getPoblacionForTable() {
        return new Object[]{this, this.provincia, this.pais};
    }

    public static void setColumns(DefaultTableModel model) {
        
        model.addColumn("Nombre");
        model.addColumn("Provincia");
        model.addColumn("Pais");
    }
    
    public String toString(){
        return this.nombre;
    }



}


