package hibernate;
// Generated 22-feb-2018 17:08:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 * Vivienda generated by hbm2java
 */
public class Vivienda  implements java.io.Serializable {


     private Integer idVivienda;
     private Poblacion poblacion;
     private String direccion;
     private Byte viviendaActiva;
     private Set personases = new HashSet(0);
     private Set personases_1 = new HashSet(0);

    public Vivienda() {
    }

	
    public Vivienda(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public Vivienda(Poblacion poblacion, String direccion, Byte viviendaActiva, Set personases, Set personases_1) {
       this.poblacion = poblacion;
       this.direccion = direccion;
       this.viviendaActiva = viviendaActiva;
       this.personases = personases;
       this.personases_1 = personases_1;
    }
   
    public Integer getIdVivienda() {
        return this.idVivienda;
    }
    
    public void setIdVivienda(Integer idVivienda) {
        this.idVivienda = idVivienda;
    }
    public Poblacion getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Byte getViviendaActiva() {
        return this.viviendaActiva;
    }
    
    public void setViviendaActiva(Byte viviendaActiva) {
        this.viviendaActiva = viviendaActiva;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }
    public Set getPersonases_1() {
        return this.personases_1;
    }
    
    public void setPersonases_1(Set personases_1) {
        this.personases_1 = personases_1;
    }

    public Object[] getViviendaForTable() {
        return new Object[]{this, this.poblacion.getNombre(), this.poblacion.getProvincia(), this.poblacion.getPais()};
    }

    public static void setColumns(DefaultTableModel model) {
        
        model.addColumn("Direccion");
        model.addColumn("Poblacion");
        model.addColumn("Provincia");
        model.addColumn("Pais");
    }
    
    public String toString(){
        return this.direccion;
    }


}


