package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer idAsistencia;
     private Asistente asistente;
     private Dependiente dependiente;
     private Date fecha;
     private String motivo;
     private String datosAsistencia;

    public Asistencia() {
    }

	
    public Asistencia(Asistente asistente, Dependiente dependiente) {
        this.asistente = asistente;
        this.dependiente = dependiente;
    }
    public Asistencia(Asistente asistente, Dependiente dependiente, Date fecha, String motivo, String datosAsistencia) {
       this.asistente = asistente;
       this.dependiente = dependiente;
       this.fecha = fecha;
       this.motivo = motivo;
       this.datosAsistencia = datosAsistencia;
    }
   
    public Integer getIdAsistencia() {
        return this.idAsistencia;
    }
    
    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }
    public Asistente getAsistente() {
        return this.asistente;
    }
    
    public void setAsistente(Asistente asistente) {
        this.asistente = asistente;
    }
    public Dependiente getDependiente() {
        return this.dependiente;
    }
    
    public void setDependiente(Dependiente dependiente) {
        this.dependiente = dependiente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getDatosAsistencia() {
        return this.datosAsistencia;
    }
    
    public void setDatosAsistencia(String datosAsistencia) {
        this.datosAsistencia = datosAsistencia;
    }




}


