package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asistente generated by hbm2java
 */
public class Asistente  implements java.io.Serializable {


     private int idAsistente;
     private Personas personas;
     private String contrasenya;
     private Set dependientes = new HashSet(0);
     private Set asistencias = new HashSet(0);
     private Set tareasPendienteses = new HashSet(0);

    public Asistente() {
    }

	
    public Asistente(Personas personas) {
        this.personas = personas;
    }
    public Asistente(Personas personas, String contrasenya, Set dependientes, Set asistencias, Set tareasPendienteses) {
       this.personas = personas;
       this.contrasenya = contrasenya;
       this.dependientes = dependientes;
       this.asistencias = asistencias;
       this.tareasPendienteses = tareasPendienteses;
    }
   
    public int getIdAsistente() {
        return this.idAsistente;
    }
    
    public void setIdAsistente(int idAsistente) {
        this.idAsistente = idAsistente;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public Set getDependientes() {
        return this.dependientes;
    }
    
    public void setDependientes(Set dependientes) {
        this.dependientes = dependientes;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }
    public Set getTareasPendienteses() {
        return this.tareasPendienteses;
    }
    
    public void setTareasPendienteses(Set tareasPendienteses) {
        this.tareasPendienteses = tareasPendienteses;
    }




}


