package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1



/**
 * DependienteHasMedicacion generated by hbm2java
 */
public class DependienteHasMedicacion  implements java.io.Serializable {


     private DependienteHasMedicacionId id;
     private Dependiente dependiente;
     private Medicacion medicacion;
     private String toma;

    public DependienteHasMedicacion() {
    }

	
    public DependienteHasMedicacion(DependienteHasMedicacionId id, Dependiente dependiente, Medicacion medicacion) {
        this.id = id;
        this.dependiente = dependiente;
        this.medicacion = medicacion;
    }
    public DependienteHasMedicacion(DependienteHasMedicacionId id, Dependiente dependiente, Medicacion medicacion, String toma) {
       this.id = id;
       this.dependiente = dependiente;
       this.medicacion = medicacion;
       this.toma = toma;
    }
   
    public DependienteHasMedicacionId getId() {
        return this.id;
    }
    
    public void setId(DependienteHasMedicacionId id) {
        this.id = id;
    }
    public Dependiente getDependiente() {
        return this.dependiente;
    }
    
    public void setDependiente(Dependiente dependiente) {
        this.dependiente = dependiente;
    }
    public Medicacion getMedicacion() {
        return this.medicacion;
    }
    
    public void setMedicacion(Medicacion medicacion) {
        this.medicacion = medicacion;
    }
    public String getToma() {
        return this.toma;
    }
    
    public void setToma(String toma) {
        this.toma = toma;
    }




}


