package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicacion generated by hbm2java
 */
public class Medicacion  implements java.io.Serializable {


     private Integer idMedicacion;
     private String nombre;
     private Set dependienteHasMedicacions = new HashSet(0);

    public Medicacion() {
    }

    public Medicacion(String nombre, Set dependienteHasMedicacions) {
       this.nombre = nombre;
       this.dependienteHasMedicacions = dependienteHasMedicacions;
    }
   
    public Integer getIdMedicacion() {
        return this.idMedicacion;
    }
    
    public void setIdMedicacion(Integer idMedicacion) {
        this.idMedicacion = idMedicacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDependienteHasMedicacions() {
        return this.dependienteHasMedicacions;
    }
    
    public void setDependienteHasMedicacions(Set dependienteHasMedicacions) {
        this.dependienteHasMedicacions = dependienteHasMedicacions;
    }




}


