package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer idPersona;
     private String dni;
     private String nombre;
     private String apellidos;
     private Date nacimiento;
     private String genero;
     private Set viviendas = new HashSet(0);
     private Dependiente dependiente;
     private Set telefonoses = new HashSet(0);
     private Asistente asistente;
     private Set dependientes = new HashSet(0);
     private Contacto contacto;

    public Personas() {
    }

    public Personas(String dni, String nombre, String apellidos, Date nacimiento, String genero, Set viviendas, Dependiente dependiente, Set telefonoses, Asistente asistente, Set dependientes, Contacto contacto) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nacimiento = nacimiento;
       this.genero = genero;
       this.viviendas = viviendas;
       this.dependiente = dependiente;
       this.telefonoses = telefonoses;
       this.asistente = asistente;
       this.dependientes = dependientes;
       this.contacto = contacto;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getNacimiento() {
        return this.nacimiento;
    }
    
    public void setNacimiento(Date nacimiento) {
        this.nacimiento = nacimiento;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Set getViviendas() {
        return this.viviendas;
    }
    
    public void setViviendas(Set viviendas) {
        this.viviendas = viviendas;
    }
    public Dependiente getDependiente() {
        return this.dependiente;
    }
    
    public void setDependiente(Dependiente dependiente) {
        this.dependiente = dependiente;
    }
    public Set getTelefonoses() {
        return this.telefonoses;
    }
    
    public void setTelefonoses(Set telefonoses) {
        this.telefonoses = telefonoses;
    }
    public Asistente getAsistente() {
        return this.asistente;
    }
    
    public void setAsistente(Asistente asistente) {
        this.asistente = asistente;
    }
    public Set getDependientes() {
        return this.dependientes;
    }
    
    public void setDependientes(Set dependientes) {
        this.dependientes = dependientes;
    }
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }




}


