package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion  implements java.io.Serializable {


     private int idPoblacion;
     private String nombre;
     private String provincia;
     private String pais;
     private Set viviendas = new HashSet(0);
     private RecursosLocalidad recursosLocalidad;

    public Poblacion() {
    }

	
    public Poblacion(int idPoblacion) {
        this.idPoblacion = idPoblacion;
    }
    public Poblacion(int idPoblacion, String nombre, String provincia, String pais, Set viviendas, RecursosLocalidad recursosLocalidad) {
       this.idPoblacion = idPoblacion;
       this.nombre = nombre;
       this.provincia = provincia;
       this.pais = pais;
       this.viviendas = viviendas;
       this.recursosLocalidad = recursosLocalidad;
    }
   
    public int getIdPoblacion() {
        return this.idPoblacion;
    }
    
    public void setIdPoblacion(int idPoblacion) {
        this.idPoblacion = idPoblacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getViviendas() {
        return this.viviendas;
    }
    
    public void setViviendas(Set viviendas) {
        this.viviendas = viviendas;
    }
    public RecursosLocalidad getRecursosLocalidad() {
        return this.recursosLocalidad;
    }
    
    public void setRecursosLocalidad(RecursosLocalidad recursosLocalidad) {
        this.recursosLocalidad = recursosLocalidad;
    }




}


