package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private TelefonosId id;
     private Personas personas;
     private String numero;
     private String tipo;

    public Telefonos() {
    }

	
    public Telefonos(TelefonosId id, Personas personas) {
        this.id = id;
        this.personas = personas;
    }
    public Telefonos(TelefonosId id, Personas personas, String numero, String tipo) {
       this.id = id;
       this.personas = personas;
       this.numero = numero;
       this.tipo = tipo;
    }
   
    public TelefonosId getId() {
        return this.id;
    }
    
    public void setId(TelefonosId id) {
        this.id = id;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


