package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1



/**
 * TelefonosId generated by hbm2java
 */
public class TelefonosId  implements java.io.Serializable {


     private int idTelefonos;
     private int idPersona;

    public TelefonosId() {
    }

    public TelefonosId(int idTelefonos, int idPersona) {
       this.idTelefonos = idTelefonos;
       this.idPersona = idPersona;
    }
   
    public int getIdTelefonos() {
        return this.idTelefonos;
    }
    
    public void setIdTelefonos(int idTelefonos) {
        this.idTelefonos = idTelefonos;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonosId) ) return false;
		 TelefonosId castOther = ( TelefonosId ) other; 
         
		 return (this.getIdTelefonos()==castOther.getIdTelefonos())
 && (this.getIdPersona()==castOther.getIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTelefonos();
         result = 37 * result + this.getIdPersona();
         return result;
   }   


}


