package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vivienda generated by hbm2java
 */
public class Vivienda  implements java.io.Serializable {


     private ViviendaId id;
     private Poblacion poblacion;
     private String direccion;
     private Set personases = new HashSet(0);

    public Vivienda() {
    }

	
    public Vivienda(ViviendaId id, Poblacion poblacion) {
        this.id = id;
        this.poblacion = poblacion;
    }
    public Vivienda(ViviendaId id, Poblacion poblacion, String direccion, Set personases) {
       this.id = id;
       this.poblacion = poblacion;
       this.direccion = direccion;
       this.personases = personases;
    }
   
    public ViviendaId getId() {
        return this.id;
    }
    
    public void setId(ViviendaId id) {
        this.id = id;
    }
    public Poblacion getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Poblacion poblacion) {
        this.poblacion = poblacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


