package modelo.hibernate;
// Generated 08-feb-2018 19:11:36 by Hibernate Tools 4.3.1



/**
 * ViviendaId generated by hbm2java
 */
public class ViviendaId  implements java.io.Serializable {


     private int idVivienda;
     private int idPoblacion;

    public ViviendaId() {
    }

    public ViviendaId(int idVivienda, int idPoblacion) {
       this.idVivienda = idVivienda;
       this.idPoblacion = idPoblacion;
    }
   
    public int getIdVivienda() {
        return this.idVivienda;
    }
    
    public void setIdVivienda(int idVivienda) {
        this.idVivienda = idVivienda;
    }
    public int getIdPoblacion() {
        return this.idPoblacion;
    }
    
    public void setIdPoblacion(int idPoblacion) {
        this.idPoblacion = idPoblacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViviendaId) ) return false;
		 ViviendaId castOther = ( ViviendaId ) other; 
         
		 return (this.getIdVivienda()==castOther.getIdVivienda())
 && (this.getIdPoblacion()==castOther.getIdPoblacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVivienda();
         result = 37 * result + this.getIdPoblacion();
         return result;
   }   


}


